In [69]:
import pickle
import pandas as pd

url=r'\\192.168.0.118\d\MachineLearning\Data\boston_X.xls'
bstn=pd.read_excel(url)
bstn.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PT,B,LSTAT
0,0.00632,18.0,2.31,0,0.538,6.575,65.199997,4.0900,1,296,15.300000,396.899994,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.900002,4.9671,2,242,17.799999,396.899994,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.099998,4.9671,2,242,17.799999,392.829987,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.799999,6.0622,3,222,18.700001,394.630005,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.200001,6.0622,3,222,18.700001,396.899994,5.33

In [70]:
#model =pickel.loads(r'C:\Users\w10\Desktop\Hp\Boston_regressor.pkl')
#with open('Boston_regressor.pkl', 'rb') as f:
#    mdl=pickle.load(f)#@
#print(mdl)
#print(type(f))

In [71]:
from sklearn.externals import joblib 
#  Save model for future use
mdl=joblib.load(r'C:\Users\w10\Desktop\Hp\Boston_regressor.pkl')
print(type(mdl))

<class 'sklearn.linear_model.base.LinearRegression'>

In [72]:
bstn.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PT,B,LSTAT
0,0.00632,18.0,2.31,0,0.538,6.575,65.199997,4.0900,1,296,15.300000,396.899994,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.900002,4.9671,2,242,17.799999,396.899994,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.099998,4.9671,2,242,17.799999,392.829987,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.799999,6.0622,3,222,18.700001,394.630005,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.200001,6.0622,3,222,18.700001,396.899994,5.33

In [73]:
bstn.shape

(506, 13)

In [76]:
predt = mdl.predict(bstn)

In [77]:
print(predt)

[30.00384239 25.02556246 30.56759657 28.60703616 27.9435227  25.25628285
 23.00180864 19.53598867 11.5236374  18.92026271 18.99949555 21.58679534
 20.90652153 19.55290243 19.28348244 19.29748365 20.52750988 16.9114003
 16.17801088 18.40613746 12.52385828 17.67103751 15.83288242 13.80628676
 15.67833795 13.38668596 15.46397713 14.70847372 19.54737257 20.87642818
 11.45511734 18.05923311  8.81105738 14.28275891 13.70675984 23.81463433
 22.34193665 23.10890974 22.91502526 31.35762528 34.21510328 28.02056404
 25.20386686 24.60979251 22.94149093 22.09669886 20.42319976 18.03655181
  9.10655491 17.20607823 21.28152511 23.97222218 27.65585159 24.04901878
 15.36184764 31.15265018 24.85686994 33.10919801 21.7753791  21.08493441
 17.87258029 18.51110154 23.98742689 22.55408828 23.37308575 30.36148326
 25.53056578 21.11338453 17.42153719 20.78483715 25.20148745 21.74265687
 24.55744917 24.04295617 25.50499525 23.96692855 22.94545258 23.3569967
 21.2619811  22.42817267 28.40577043 26.99486074 26.03576308 25.05873402
 24.78456667 27.79049244 22.16853402 25.89276346 30.67461895 30.83110714
 27.11901935 27.41266912 28.94122698 29.08105471 27.03977328 28.62459978
 24.72745023 35.78159628 35.1145468  32.25102775 24.58022173 25.59413569
 19.79013834 20.31167257 21.43482598 18.53994043 17.18756075 20.75049029
 22.6482915  19.77203779 20.64965979 26.52586894 20.77323828 20.71548379
 25.17209041 20.43025667 23.37724763 23.69043307 20.33578552 20.79180945
 21.91632049 22.47107839 20.5573854  16.36661986 20.5609992  22.48178452
 14.61706612 15.17876479 18.93868561 14.05573206 20.03527361 19.41013383
 20.06191572 15.75807619 13.25645173 17.26277729 15.87841774 19.36163837
 13.81483781 16.44881432 13.57141753  3.9888544  14.59495481 12.14881472
  8.72822285 12.03585456 15.82082029  8.51499046  9.71844125 14.80451423
 20.83858232 18.30101156 20.1228262  17.28601974 22.36600325 20.10375917
 13.62125888 33.25982602 29.03017267 25.56752891 32.70827656 36.77466924
 40.5576584  41.84728176 24.78867376 25.3788913  37.20347371 23.08748662
 26.40273841 26.65382097 22.55514639 24.29082857 22.97657214 29.07194238
 26.52194391 30.7220905  25.6166932  29.13740974 31.43572003 32.92231636
 34.72440487 27.76552212 33.88787465 30.99238197 22.71820128 24.76647828
 35.8849726  33.42476763 32.41199245 34.51509939 30.76109539 30.28934045
 32.91918675 32.11260775 31.55870991 40.84555807 36.12770082 32.66920714
 34.70469134 30.09345137 30.64394006 29.28719604 37.07148488 42.03193211
 43.1895     22.69034695 23.68284768 17.85447225 23.49429016 17.00587629
 22.39251065 17.06042677 22.73892918 25.21942522 11.11916801 24.51049176
 26.60334788 28.35518839 24.91525535 29.68652817 33.18419812 23.77456678
 32.14052015 29.74581989 38.37102409 39.81462046 37.58605774 32.39953306
 35.45665234 31.23411563 24.48449259 33.288374   38.04810442 37.16328518
 31.71383436 25.26705529 30.10010794 32.71987106 28.42717003 28.42940633
 27.29375813 23.74262357 24.12007752 27.40208402 16.32857532 13.39891327
 20.01638671 19.86184367 21.28831295 24.07989102 24.20633525 25.04215898
 24.91963876 29.94563259 23.97228341 21.69580948 37.51109272 43.30239214
 36.48361468 34.9898856  34.81211505 37.1663127  40.98928368 34.44634135
 35.83397462 28.24574252 31.22673551 40.83955735 39.31792322 25.70817935
 22.30295509 27.20340872 28.51169488 35.47676588 36.1063909  33.79668252
 35.61085896 34.83993434 30.35192598 35.3098067  38.79757097 34.33123203
 40.33963073 44.67308213 31.59688981 27.35659251 20.10174093 27.04206652
 27.21364537 26.91395785 33.43563211 34.40349419 31.83339747 25.81783191
 24.42982307 28.45764296 27.36266904 19.53928694 29.11309767 31.91054569
 30.77159356 28.94275872 28.88190904 32.79887112 33.20905537 30.76831877
 35.56226921 32.70905141 28.64244285 23.58965838 18.5426691  26.87889896
 23.28133829 25.54580162 25.48120033 20.53909876 17.61572582 18.3758169
 24.29070253 21.32528995 24.88682251 24.86937212 22.86952393 19.45123861
 25.11783371 24.66786927 23.68076018 19.34089611 21.17418115 24.25249137
 21.59260934 19.98446566 23.338881   22.14060674 21.55509888 20.618729
 20.16097085 19.28490342 22.1667227  21.24965774 21.42939219 30.32788866
 22.04734987 27.70647921 28.54794075 16.54501143 14.7835955  25.27380006
 27.54205236 22.14837577 20.45943953 20.54605415 16.88063732 25.40253548
 14.32486667 16.59488426 19.63704604 22.71806548 22.20218795 19.20548007
 22.66615986 18.93192564 18.22846788 20.23150745 37.49447209 14.28190737
 15.54286113 10.83162263 23.80072775 32.64407348 34.60683914 24.94331327
 25.99980859  6.12632473  0.7777971  25.3071307  17.74061049 20.23274391
 15.83331234 16.83512483 14.36994809 18.47682785 13.42768117 13.06177477
  3.27918114  8.06022121  6.12842071  5.6186478   6.45198537 14.20764616
 17.2122503  17.29887262  9.89116489 20.2212401  17.94181078 20.30445713
 19.29559    16.33632764  6.55162246 10.89016814 11.88145732 17.81174381
 18.26126415 12.97948625  7.37816336  8.2111582   8.06626159 19.98294663
 13.70756365 19.85268431 15.22308235 16.96071957  1.71851695 11.80578389
 -4.28131154  9.58376672 13.36660686  6.89562251  6.14779577 14.60661698
 19.600025   18.1242744  18.52176902 13.1752851  14.62617609  9.92374862
 16.34590578 14.07519349 14.2575605  13.04234733 18.15955676 18.69554332
 21.52728314 17.03141786 15.96090442 13.36141553 14.52079326  8.81975861
  4.86750963 13.06591217 12.70609535 17.29557994 18.74048342 18.05900979
 11.51474586 11.97400338 17.68344514 18.12695086 17.51834591 17.22742394
 16.52271551 19.41291126 18.58215102 22.48944792 15.2800018  15.82089332
 12.68725431 12.87633634 17.18668535 18.51247491 19.04860523 20.17208835
 19.77407215 22.42940714 20.31911871 17.88616163 14.37478573 16.94776754
 16.98405794 18.58838277 20.16719265 22.97717991 22.45580604 25.57824508
 16.39147609 16.11146271 20.53481545 11.54272619 19.20496143 21.86276336
 23.46878824 27.09887242 28.56994165 21.08398744 19.45516051 22.22225767
 19.65591824 21.32536134 11.8558366   8.22386649  3.66399539 13.75908374
 15.9311836  20.62661911 20.61249403 16.88541951 14.01320733 19.10854145
 21.29805141 18.45498692 20.46870799 23.53333989 22.37571836 27.6274252
 26.12796718 22.34421257]